### ISSUE TITLE
about missing data for test

### ISSUE THREAD

**Issue by ziping46** [theleokul/dineof3#23]
hello 
 i want to use this great job to process my own data,but when i test the code ,i fond the data was missed. so i can't know whether the enviroment built correctly in UBUNTU(i am new to Linux). can you help me

**Comment by theleokul** [comment]
Hello! Thank you for your interest! Currently this repo is a bit "undercooked". Tests aren't ready, so it is ok. Basically currently this repo can be used, but it potentially has bugs and also the structure is not in the final shape. Recently I picked out some time to finish it (fully transfer to python3 + add support of the dineof modifications) and I am working on it right now. For now you may use it not in black box fashion. I expect to finish the main part this month (April 2021).
